# Generated by Django 2.0.2 on 2018-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
                ('context_text', models.CharField(max_length=1000)),
                ('question_text', models.CharField(max_length=200)),
                ('answer_start', models.IntegerField()),
                ('answer_end', models.IntegerField()),
                ('answer_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Context',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
