# Generated by Django 2.0.2 on 2018-02-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20180204_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='cqa',
            name='valid',
            field=models.IntegerField(default=0),
        ),
    ]
